baseURL = "/"
languageCode = "en-us"
title = "Yggdrasil"
theme = "kube"
description = "Yggdrasil er verdenstreet i norrøn mytologi, en ask med grener som rekker ut over hele verden og opp over himmelen."
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "raynald" # add your company name
  github = "raynald" # add your github profile name
  twitter = "raynaldchung" # add your twitter profile
  email = "ray97@163.com"

[[menu.main]]
    name = "Wikis"
    weight = -100
    url = "/wikis/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
